"""empty message

Revision ID: ff3ffb9ac04d
Revises: 32bdfc640288
Create Date: 2021-02-16 14:31:02.320991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3ffb9ac04d'
down_revision = '32bdfc640288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artists_showid_fkey', 'artists', type_='foreignkey')
    op.drop_column('artists', 'showid')
    op.add_column('shows', sa.Column('artistid', sa.Integer(), nullable=True))
    op.add_column('shows', sa.Column('venueid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shows', 'venues', ['venueid'], ['id'])
    op.create_foreign_key(None, 'shows', 'artists', ['artistid'], ['id'])
    op.drop_constraint('venues_showid_fkey', 'venues', type_='foreignkey')
    op.drop_column('venues', 'showid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('showid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('venues_showid_fkey', 'venues', 'shows', ['showid'], ['id'])
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'venueid')
    op.drop_column('shows', 'artistid')
    op.add_column('artists', sa.Column('showid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('artists_showid_fkey', 'artists', 'shows', ['showid'], ['id'])
    # ### end Alembic commands ###
